=== IvernIt/IvernIt_server/xml/Resultados.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="resultados">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="resultado" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="agua" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="minInclusive" minOccurs="0" maxOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:integer">
                          <xs:minInclusive value="0"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="maxInclusive" minOccurs="0" maxOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:integer">
                          <xs:minInclusive value="1"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="luz" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="minInclusive" minOccurs="0" maxOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:integer">
                          <xs:minInclusive value="0"/>
                          <xs:maxInclusive value="23"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="maxInclusive" minOccurs="0" maxOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:integer">
                          <xs:minInclusive value="1"/>
                          <xs:maxInclusive value="24"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="temperatura" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="minInclusive" minOccurs="0" maxOccurs="1" type="xs:integer"/>
                    <xs:element name="maxInclusive" minOccurs="0" maxOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:integer">
                          <xs:minInclusive value="1"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="tierra" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="arcilloso"/>
                    <xs:enumeration value="limoso"/>
                    <xs:enumeration value="arenoso"/>
                    <xs:enumeration value="margoso"/>
                    <xs:enumeration value="gredoso"/>
                    <xs:enumeration value="pantanoso"/>
                  </xs:restriction>             
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== IvernIt/IvernIt_server/xml/testing.xml
<?xml version="1.0" encoding="UTF-8"?>
<resultados  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="Resultados.xsd">
  <resultado>
    <agua>
      <maxInclusive>5</maxInclusive>
    </agua>
    <luz>
      <maxInclusive>8</maxInclusive>
      <minInclusive>7</minInclusive>
    </luz>
    <temperatura>
      <maxInclusive>22</maxInclusive>
    </temperatura>
    <tierra>gredoso</tierra>
  </resultado>
</resultados>
